# Generated by Django 5.1.7 on 2025-04-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
    ]
