# Generated by Django 5.1.6 on 2025-03-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_starts',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
