# Generated by Django 5.1.6 on 2025-03-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_group_lesson_starts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
