# Generated by Django 5.1.6 on 2025-03-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_group_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
