# Generated by Django 5.1.7 on 2025-04-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_end_time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
