# Generated by Django 5.1.7 on 2025-04-12 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_group_lesson_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
