# Generated by Django 5.1.7 on 2025-04-12 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_staffs_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'svg'])]),
        ),
    ]
